import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header'
import Head from "next/head";

export const metadata: Metadata = {
  title: "Nextjs Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
